spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: curso
    password: 
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect